version: '3.4'

services:

  corehome.database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

  corehome.homepage:
    image: corehome.homepage
    build:
      context: ../
      dockerfile: CoreHome.HomePage/Dockerfile
    depends_on:
      - corehome.database
    restart: always
    volumes:
      - server:/home

  corehome.admin:
    image: corehome.admin
    build:
      context: ../
      dockerfile: CoreHome.Admin/Dockerfile
    depends_on:
      - corehome.database
    restart: always
    volumes:
      - server:/home

  corehome.reverseproxy:
    image: corehome.reverseproxy
    build:
      context: ../
      dockerfile: CoreHome.ReverseProxy/Dockerfile
    depends_on:
      - corehome.homepage
      - corehome.admin
    ports:
      - "8080:8080"

volumes:
  db:
  server:
